# Generated by Django 5.2.4 on 2025-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Название иконки Bootstrap, например: 'bi-spa'",
                max_length=50,
                verbose_name="Bootstrap иконка",
            ),
        ),
    ]
