# Generated by Django 5.2.4 on 2025-07-25 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("locations", "0002_location_latitude_location_longitude"),
        ("services", "0002_servicecategory_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Эти заметки видны только администраторам",
                verbose_name="Заметки администратора",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notified",
            field=models.BooleanField(default=False, verbose_name="Клиент уведомлен"),
        ),
        migrations.AddField(
            model_name="review",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="locations.location",
                verbose_name="Филиал",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="appointments.appointment",
                verbose_name="Запись",
            ),
        ),
    ]
