# Generated by Django 5.2.4 on 2025-08-07 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar_type",
                    models.CharField(
                        choices=[
                            ("none", "Не использовать"),
                            ("google", "Google Calendar"),
                            ("ical", "iCalendar (Apple, Outlook и др.)"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Тип календаря",
                    ),
                ),
                (
                    "add_appointments",
                    models.BooleanField(
                        default=True, verbose_name="Добавлять новые записи в календарь"
                    ),
                ),
                (
                    "update_appointments",
                    models.BooleanField(
                        default=True,
                        verbose_name="Обновлять измененные записи в календаре",
                    ),
                ),
                (
                    "remove_canceled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Удалять отмененные записи из календаря",
                    ),
                ),
                (
                    "reminder_time",
                    models.IntegerField(
                        default=60, verbose_name="Время напоминания (в минутах)"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки календаря",
                "verbose_name_plural": "Настройки календарей",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.JSONField(verbose_name="Токен доступа")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Учетные данные Google Calendar",
                "verbose_name_plural": "Учетные данные Google Calendar",
            },
        ),
    ]
