# Generated by Django 5.2.4 on 2025-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.CharField(
                blank=True, default="53.2007", max_length=20, verbose_name="Широта"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.CharField(
                blank=True, default="45.0046", max_length=20, verbose_name="Долгота"
            ),
        ),
    ]
